name: Build Windows App

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pillow
        pip install requests
        pip install paho-mqtt
        pip install opencv-python
        
    - name: Create Icon (if missing)
      run: |
        if (-not (Test-Path "icon.ico")) {
          echo "Creating dummy icon..."
          python -c "
        from PIL import Image
        import os
        if not os.path.exists('icon.ico'):
            img = Image.new('RGB', (32, 32), color='blue')
            img.save('icon.ico', format='ICO')
        "
        }
      shell: powershell
      
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile ^
          --windowed ^
          --icon=icon.ico ^
          --hidden-import=PIL ^
          --hidden-import=PIL.Image ^
          --hidden-import=PIL.ImageTk ^
          --hidden-import=cv2 ^
          --hidden-import=paho.mqtt.client ^
          --hidden-import=tkinter ^
          --hidden-import=tkinter.ttk ^
          --hidden-import=tkinter.font ^
          --hidden-import=tkinter.filedialog ^
          --hidden-import=tkinter.messagebox ^
          --name="3D-Drucker-Widget" ^
          ha-widget.py
      shell: cmd
      
    - name: Create Release Package
      run: |
        mkdir release
        copy dist\3D-Drucker-Widget.exe release\
        if (Test-Path "README.md") { copy README.md release\ }
        if (Test-Path "icon.ico") { copy icon.ico release\ }
      shell: powershell
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 3D-Drucker-Widget-Windows
        path: release/
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: release/3D-Drucker-Widget.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}